# Generated by Django 5.1.1 on 2024-09-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_song_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
            ],
        ),
    ]
